name: Building and Pushing Docker Image for the Main Server
run-name: Building and Pushing Docker Image for the Main Server

on:
  push:
    branches:
      - main
    paths:
      - apps/main-server/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-workspace:newsletter-main-server
          build-args: |
            WORKSPACE=newsletter-main-server
            APP=main-server
